### ISSUE TITLE
CommonsChunkPlugin被注释了？

### ISSUE THREAD

**Issue by C-Coding** [YaoZeyuan/vue-multi-page#3]
为什么呢，多项目更有必要单独打包公用库吧

**Comment by YaoZeyuan** [comment]
我们的多项目更多的是指多个独立的项目，用户同一时间访问不同项目的可能性很小(比如活动页，很少有用户参加完签到活动再去参加摇奖活动的), 所以在多项目模板中，反而没必要提取公共库：）
